### ISSUE TITLE
(Response to Feedback Item 18) Add non-normative mention of shibmd:scope in SDP-SP20

### ISSUE THREAD

**Issue by judielaine** [KantaraInitiative/SAMLprofiles#95]

**Comment by judielaine** [comment]
If shibmd:scope is included, it is likely only relevant in our R&E context. Can’t put a shibboleth-specific thing into the doc as normative, but could certainly mention it
 Genesis of the issue where shibmd:scope had been normatively defined as case-sensitive, and software was not honoring that
Scott will clean up the shibboleth wiki doc on this topic to remove ‘under development’ and get the non-normative text added here that references the shibboleth docs.
Can say things like ‘domain-like syntax, authorizing specific domains, metadata used for authorizing these domains’
Will reference OASIS identifiers spec

**Comment by scantor** [comment]
OASIS has indicated we can propose standardization of this extension without renaming it, so the plan is to do so in the subject-id draft and then update the language here to reflect that. Unclear at this point to what degree it would be normative since this is really about policy. We should at least reference it certainly.

**Comment by scantor** [comment]
A new OASIS draft was pre-circulated to our group today for comment. Once that's done, we'll tackle revising the material in here.

**Comment by scantor** [comment]
Noting I submitted a working draft to OASIS with the additional work. Next step is the text on this side.

**Comment by scantor** [comment]
This never got closed.
